export const SITE_NAME = 'rechner360.de';
export const SITE_URL = 'https://www.rechner360.de';
// Meta-Description: 151 Zeichen — innerhalb des SERP-Limits von ~155 Zeichen.
export const SITE_DESCRIPTION = '27 kostenlose Online-Rechner 2026 für Finanzen, Steuern & Versicherungen. Keine Registrierung — alle Berechnungen laufen direkt im Browser.';

export const BUNDESLAENDER = [
  { id: 'bw', name: 'Baden-Württemberg', kirchensteuer: 0.08 },
  { id: 'by', name: 'Bayern', kirchensteuer: 0.08 },
  { id: 'be', name: 'Berlin', kirchensteuer: 0.09 },
  { id: 'bb', name: 'Brandenburg', kirchensteuer: 0.09 },
  { id: 'hb', name: 'Bremen', kirchensteuer: 0.09 },
  { id: 'hh', name: 'Hamburg', kirchensteuer: 0.09 },
  { id: 'he', name: 'Hessen', kirchensteuer: 0.09 },
  { id: 'mv', name: 'Mecklenburg-Vorpommern', kirchensteuer: 0.09 },
  { id: 'ni', name: 'Niedersachsen', kirchensteuer: 0.09 },
  { id: 'nw', name: 'Nordrhein-Westfalen', kirchensteuer: 0.09 },
  { id: 'rp', name: 'Rheinland-Pfalz', kirchensteuer: 0.09 },
  { id: 'sl', name: 'Saarland', kirchensteuer: 0.09 },
  { id: 'sn', name: 'Sachsen', kirchensteuer: 0.09 },
  { id: 'st', name: 'Sachsen-Anhalt', kirchensteuer: 0.09 },
  { id: 'sh', name: 'Schleswig-Holstein', kirchensteuer: 0.09 },
  { id: 'th', name: 'Thüringen', kirchensteuer: 0.09 },
] as const;

export type BundeslandId = typeof BUNDESLAENDER[number]['id'];

export const STEUERKLASSEN = [
  { id: 1, name: 'Steuerklasse I', description: 'Ledige, Geschiedene, Verwitwete' },
  { id: 2, name: 'Steuerklasse II', description: 'Alleinerziehende' },
  { id: 3, name: 'Steuerklasse III', description: 'Verheiratete (höheres Einkommen)' },
  { id: 4, name: 'Steuerklasse IV', description: 'Verheiratete (gleiches Einkommen)' },
  { id: 5, name: 'Steuerklasse V', description: 'Verheiratete (niedrigeres Einkommen)' },
  { id: 6, name: 'Steuerklasse VI', description: 'Zweit- und Nebenjobs' },
] as const;

export type SteuerklasseId = typeof STEUERKLASSEN[number]['id'];

export const RECHNER_CATEGORIES = [
  {
    id: 'gehalt-steuern',
    title: 'Gehalt & Steuern',
    description: 'Brutto-Netto, Gehaltsvergleich, Stundenlohn und Abfindung berechnen.',
    icon: 'wallet',
    color: 'primary',
  },
  {
    id: 'immobilien-finanzen',
    title: 'Immobilien & Finanzen',
    description: 'Kredit, Tilgung, Baukosten, Nebenkosten und Zinsen berechnen.',
    icon: 'landmark',
    color: 'accent',
  },
  {
    id: 'vorsorge-soziales',
    title: 'Vorsorge & Soziales',
    description: 'Elterngeld, Rente, Unterhalt, Bürgergeld und Pfändung berechnen.',
    icon: 'shield-check',
    color: 'primary',
  },
  {
    id: 'alltag-tools',
    title: 'Alltag & Tools',
    description: 'Prozent, MwSt, BMI, Kalorien und Inflation berechnen.',
    icon: 'percent',
    color: 'accent',
  },
] as const;

export type CategoryId = typeof RECHNER_CATEGORIES[number]['id'];

export const RECHNER = [
  {
    slug: 'brutto-netto-rechner',
    title: 'Brutto Netto Rechner',
    shortTitle: 'Brutto-Netto',
    description: 'Berechnen Sie schnell und genau, wie viel Netto von Ihrem Bruttogehalt übrig bleibt.',
    icon: 'calculator',
    color: 'primary',
    popular: true,
    category: 'gehalt-steuern' as CategoryId,
  },
  {
    slug: 'gehaltserhoehung-rechner',
    title: 'Gehaltserhöhung Rechner',
    shortTitle: 'Erhöhung',
    description: 'Berechnen Sie, wie viel von einer Gehaltserhöhung netto übrig bleibt.',
    icon: 'arrow-up-right',
    color: 'accent',
    popular: false,
    category: 'gehalt-steuern' as CategoryId,
  },
  {
    slug: 'gehaltsrechner',
    title: 'Gehaltsrechner',
    shortTitle: 'Gehalt',
    description: 'Vergleichen Sie Ihr Gehalt über alle Steuerklassen und berechnen Sie die Arbeitgeberkosten.',
    icon: 'wallet',
    color: 'accent',
    popular: true,
    category: 'gehalt-steuern' as CategoryId,
  },
  {
    slug: 'kreditrechner',
    title: 'Kreditrechner',
    shortTitle: 'Kredit',
    description: 'Berechnen Sie die monatliche Rate, Gesamtkosten und Zinsen für Ihren Kredit.',
    icon: 'landmark',
    color: 'primary',
    popular: true,
    category: 'immobilien-finanzen' as CategoryId,
  },
  {
    slug: 'tilgungsrechner',
    title: 'Tilgungsrechner',
    shortTitle: 'Tilgung',
    description: 'Erstellen Sie einen detaillierten Tilgungsplan für Ihre Baufinanzierung.',
    icon: 'home',
    color: 'accent',
    popular: true,
    category: 'immobilien-finanzen' as CategoryId,
  },
  {
    slug: 'bmi-rechner',
    title: 'BMI Rechner',
    shortTitle: 'BMI',
    description: 'Berechnen Sie Ihren Body-Mass-Index und erfahren Sie, ob Ihr Gewicht im gesunden Bereich liegt.',
    icon: 'heart-pulse',
    color: 'accent',
    popular: true,
    category: 'alltag-tools' as CategoryId,
  },
  {
    slug: 'elterngeld-rechner',
    title: 'Elterngeld Rechner',
    shortTitle: 'Elterngeld',
    description: 'Berechnen Sie Ihr Elterngeld \u2014 Basiselterngeld oder ElterngeldPlus mit Geschwisterbonus.',
    icon: 'baby',
    color: 'primary',
    popular: true,
    category: 'vorsorge-soziales' as CategoryId,
  },
  {
    slug: 'prozentrechner',
    title: 'Prozentrechner',
    shortTitle: 'Prozent',
    description: 'Prozente berechnen: Anteil, Prozentsatz, Grundwert und prozentuale Ver\u00e4nderung.',
    icon: 'percent',
    color: 'primary',
    popular: true,
    category: 'alltag-tools' as CategoryId,
  },
  {
    slug: 'mwst-rechner',
    title: 'MwSt Rechner',
    shortTitle: 'MwSt',
    description: 'Mehrwertsteuer berechnen: Netto zu Brutto und Brutto zu Netto mit 19% oder 7% MwSt.',
    icon: 'receipt',
    color: 'primary',
    popular: false,
    category: 'alltag-tools' as CategoryId,
  },
  {
    slug: 'stundenlohn-rechner',
    title: 'Stundenlohn Rechner',
    shortTitle: 'Stundenlohn',
    description: 'Rechnen Sie Stundenlohn in Monatsgehalt und Jahresgehalt um \u2014 und umgekehrt.',
    icon: 'briefcase',
    color: 'accent',
    popular: false,
    category: 'gehalt-steuern' as CategoryId,
  },
  {
    slug: 'zinseszinsrechner',
    title: 'Zinseszinsrechner',
    shortTitle: 'Zinseszins',
    description: 'Berechnen Sie, wie Ihr Geld durch Zinseszins w\u00e4chst. Mit Sparrate, Laufzeit und Zinssatz.',
    icon: 'trending-up',
    color: 'accent',
    popular: false,
    category: 'immobilien-finanzen' as CategoryId,
  },
  {
    slug: 'rentenrechner',
    title: 'Rentenrechner',
    shortTitle: 'Rente',
    description: 'Berechnen Sie Ihre voraussichtliche gesetzliche Rente mit Entgeltpunkten und Rentenl\u00fccke.',
    icon: 'milestone',
    color: 'accent',
    popular: false,
    category: 'vorsorge-soziales' as CategoryId,
  },
  {
    slug: 'grundsteuer-rechner',
    title: 'Grundsteuer Rechner',
    shortTitle: 'Grundsteuer',
    description: 'Berechnen Sie Ihre neue Grundsteuer nach der Reform 2025 mit Bodenrichtwert und Hebesatz.',
    icon: 'map-pin',
    color: 'primary',
    popular: false,
    category: 'immobilien-finanzen' as CategoryId,
  },
  {
    slug: 'unterhalt-rechner',
    title: 'Unterhalt Rechner',
    shortTitle: 'Unterhalt',
    description: 'Berechnen Sie den Kindesunterhalt nach der D\u00fcsseldorfer Tabelle 2025/2026.',
    icon: 'users',
    color: 'primary',
    popular: false,
    category: 'vorsorge-soziales' as CategoryId,
  },
  {
    slug: 'baukosten-rechner',
    title: 'Baukosten Rechner',
    shortTitle: 'Baukosten',
    description: 'Berechnen Sie die Baukosten f\u00fcr Ihr Haus: pro m\u00b2, nach Ausstattung, mit Keller, Garage und Nebenkosten.',
    icon: 'hard-hat',
    color: 'accent',
    popular: false,
    category: 'immobilien-finanzen' as CategoryId,
  },
  {
    slug: 'abfindungsrechner',
    title: 'Abfindungsrechner',
    shortTitle: 'Abfindung',
    description: 'Berechnen Sie die Steuer auf Ihre Abfindung mit der F\u00fcnftelregelung und sehen Sie Ihre Netto-Abfindung.',
    icon: 'banknote',
    color: 'accent',
    popular: false,
    category: 'gehalt-steuern' as CategoryId,
  },
  {
    slug: 'inflationsrechner',
    title: 'Inflationsrechner',
    shortTitle: 'Inflation',
    description: 'Berechnen Sie den Kaufkraftverlust durch Inflation \u00fcber beliebige Zeitr\u00e4ume.',
    icon: 'trending-down',
    color: 'primary',
    popular: false,
    category: 'alltag-tools' as CategoryId,
  },
  {
    slug: 'kalorienrechner',
    title: 'Kalorienrechner',
    shortTitle: 'Kalorien',
    description: 'Berechnen Sie Ihren t\u00e4glichen Kalorienbedarf: Grundumsatz, Gesamtumsatz und Zielkalorien.',
    icon: 'flame',
    color: 'accent',
    popular: false,
    category: 'alltag-tools' as CategoryId,
  },
  {
    slug: 'pfaendungsrechner',
    title: 'Pf\u00e4ndungsrechner',
    shortTitle: 'Pf\u00e4ndung',
    description: 'Berechnen Sie Ihre Pf\u00e4ndungsfreigrenze und den pf\u00e4ndbaren Betrag Ihres Einkommens.',
    icon: 'scale',
    color: 'primary',
    popular: false,
    category: 'vorsorge-soziales' as CategoryId,
  },
  {
    slug: 'nebenkostenrechner',
    title: 'Nebenkostenrechner',
    shortTitle: 'Nebenkosten',
    description: 'Berechnen Sie die Kaufnebenkosten beim Immobilienkauf: Grunderwerbsteuer, Notar, Grundbuch und Makler.',
    icon: 'building',
    color: 'accent',
    popular: false,
    category: 'immobilien-finanzen' as CategoryId,
  },
  {
    slug: 'buergergeld-rechner',
    title: 'Grundsicherung Rechner',
    shortTitle: 'Grundsicherung',
    description: 'Berechnen Sie Ihren Grundsicherungs-Anspruch 2026 (ehem. B\u00fcrgergeld) mit Regelbedarf, Kosten der Unterkunft und Freibetr\u00e4gen.',
    icon: 'shield-check',
    color: 'accent',
    popular: false,
    category: 'vorsorge-soziales' as CategoryId,
  },
  {
    slug: 'erbschaftsteuer-rechner',
    title: 'Erbschaftsteuer Rechner',
    shortTitle: 'Erbschaftsteuer',
    description: 'Berechnen Sie die Erbschaftsteuer oder Schenkungsteuer mit allen Freibeträgen und Steuerklassen.',
    icon: 'scroll',
    color: 'primary',
    popular: false,
    category: 'gehalt-steuern' as CategoryId,
  },
  {
    slug: 'pkv-rechner',
    title: 'PKV Rechner',
    shortTitle: 'PKV',
    description: 'Vergleichen Sie GKV und PKV — lohnt sich ein Wechsel in die private Krankenversicherung?',
    icon: 'shield-check',
    color: 'accent',
    popular: true,
    category: 'vorsorge-soziales' as CategoryId,
  },
  {
    slug: 'kfz-versicherung-rechner',
    title: 'Kfz-Versicherung Rechner',
    shortTitle: 'Kfz-Versicherung',
    description: 'Berechnen Sie Ihre Kfz-Versicherung: Haftpflicht, Teilkasko und Vollkasko im Vergleich.',
    icon: 'car',
    color: 'primary',
    popular: true,
    category: 'vorsorge-soziales' as CategoryId,
  },
  {
    slug: 'bu-rechner',
    title: 'BU-Rechner',
    shortTitle: 'Berufsunfähigkeit',
    description: 'Berechnen Sie den Beitrag für Ihre Berufsunfähigkeitsversicherung nach Alter und Beruf.',
    icon: 'shield-check',
    color: 'accent',
    popular: true,
    category: 'vorsorge-soziales' as CategoryId,
  },
  {
    slug: 'einkommensteuer-rechner',
    title: 'Einkommensteuerrechner',
    shortTitle: 'Einkommensteuer',
    description: 'Berechnen Sie Ihre Einkommensteuer 2026 mit Grenzsteuersatz, Solidaritätszuschlag und Kirchensteuer.',
    icon: 'receipt',
    color: 'primary',
    popular: true,
    category: 'gehalt-steuern' as CategoryId,
  },
  {
    slug: 'wohngeld-rechner',
    title: 'Wohngeldrechner',
    shortTitle: 'Wohngeld',
    description: 'Berechnen Sie Ihr Wohngeld 2026 mit Wohngeld-Plus, Heizkosten-Entlastung und Klimakomponente.',
    icon: 'home',
    color: 'primary',
    popular: true,
    category: 'vorsorge-soziales' as CategoryId,
  },
] as const;

export type RechnerSlug = typeof RECHNER[number]['slug'];

export function getRechnerByCategory(categoryId: CategoryId) {
  return RECHNER.filter((r) => r.category === categoryId);
}

export function getCategoryForRechner(slug: string) {
  const rechner = RECHNER.find((r) => r.slug === slug);
  if (!rechner) return undefined;
  return RECHNER_CATEGORIES.find((c) => c.id === rechner.category);
}
